# phaneslight-template v3.7.2 doc-index
# Regenerates every _index.md under the documentation tree (archive/ excluded). SOLE WRITER of
# indexes; hand-editing them is forbidden. Each entry is extracted in fallback order: DOC header
# line, then first heading, then humanized filename, so files predating the discipline are indexed
# without being edited. Entries are ordered by FILENAME, ordinal, descending (v3.6.1, was
# modification time), so a sequenced folder's newest entry is its first line and editing an old
# document does not reorder the index. Rotates an index past the 500-line ceiling: first ~100
# entries stay inline, the rest collapse into a range line pointing to a frozen _index_archive.md.
# Always exits 0.
$ErrorActionPreference = 'Stop'
$INLINE = 100
$UTF8_NO_BOM = New-Object System.Text.UTF8Encoding($false)
function Write-Utf8([string]$path, [string]$content) {
  [System.IO.File]::WriteAllText($path, $content, $UTF8_NO_BOM)
}

function Find-PhanesLightRoot {
  $d = (Get-Location).Path
  while ($true) {
    if (Test-Path -LiteralPath (Join-Path $d '.phaneslight\config.json')) { return $d }
    $p = [System.IO.Path]::GetDirectoryName($d)
    if (-not $p -or $p -eq $d) { return $null }
    $d = $p
  }
}

$root = Find-PhanesLightRoot
if (-not $root) { [Console]::Error.WriteLine('doc-index: .phaneslight/config.json not found from this directory'); exit 0 }

$cfg = $null
try {
  $cfg = Get-Content -LiteralPath (Join-Path $root '.phaneslight\config.json') -Raw -Encoding utf8 | ConvertFrom-Json
} catch {
  [Console]::Error.WriteLine('doc-index: .phaneslight/config.json is malformed, using defaults')
  $cfg = $null
}
$docRoot = 'documentation'
if ($cfg.docRoot) { $docRoot = $cfg.docRoot }
# A trailing slash in docRoot would otherwise leak into every derived path and message
# (doubled separators, and an empty final segment where a folder name belongs).
$docRoot = ([string]$docRoot).TrimEnd('/', '\')
if (-not $docRoot) { $docRoot = 'documentation' }
$docPath = Join-Path $root $docRoot
if (-not (Test-Path -LiteralPath $docPath)) { Write-Output 'doc-index: no documentation tree'; exit 0 }
$docPath = (Resolve-Path -LiteralPath $docPath).Path

function Get-DisciplineList([object]$cfg, [string]$key, [string]$docRoot) {
  $out = New-Object System.Collections.Generic.List[string]
  if (-not $cfg.doc_discipline) { return $out }
  $raw = $cfg.doc_discipline.$key
  if (-not $raw) { return $out }
  $prefix = $docRoot.Trim('/').Trim('\') + '/'
  foreach ($e in @($raw)) {
    if (-not $e) { continue }
    $n = ([string]$e).Trim()
    if (-not $n) { continue }
    $n = $n -replace '\\', '/'
    $n = $n.Trim('/')
    if ($n.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
      $n = $n.Substring($prefix.Length).Trim('/')
    }
    if ($n) { $out.Add($n) }
  }
  return $out
}

$exclusions = Get-DisciplineList $cfg 'index_exclusions' $docRoot
function Test-Excluded([string]$folder) {
  $rel = $folder.Substring($docPath.Length).Trim('\').Trim('/') -replace '\\', '/'
  foreach ($e in $exclusions) {
    if ($e -notmatch '/') {
      foreach ($seg in ($rel -split '/')) { if ($seg -eq $e) { return $true } }
    } else {
      if ($rel -eq $e -or $rel.StartsWith($e + '/', [System.StringComparison]::OrdinalIgnoreCase)) { return $true }
    }
  }
  return $false
}

function Get-DocLine([string]$file) {
  $desc = $null
  try { $head = Get-Content -LiteralPath $file -TotalCount 8 -Encoding utf8 } catch { $head = @() }
  foreach ($ln in $head) {
    $m = [regex]::Match($ln, '<!--\s*DOC\s*\|\s*(.+?)\s*-->')
    if ($m.Success) { return $m.Groups[1].Value.Trim() }
  }
  foreach ($ln in $head) {
    $m = [regex]::Match($ln, '^\#{1,6}\s+(.+?)\s*$')
    if ($m.Success) { return $m.Groups[1].Value.Trim() }
  }
  $base = [System.IO.Path]::GetFileNameWithoutExtension($file)
  return ($base -replace '[-_]', ' ')
}

$written = 0

function Build-Index([string]$folder) {
  $name = Split-Path -Leaf $folder
  if ($name -eq 'archive') { return }
  if (Test-Excluded $folder) { return }

  $children = Get-ChildItem -LiteralPath $folder -Force -ErrorAction SilentlyContinue
  $subfolders = @($children | Where-Object { $_.PSIsContainer -and $_.Name -ne 'archive' })
  $mdFiles = @($children | Where-Object { -not $_.PSIsContainer -and $_.Extension -eq '.md' -and $_.Name -ne '_index.md' -and $_.Name -ne '_index_archive.md' })

  # Recurse first so subfolder indexes exist before we link them.
  foreach ($sf in $subfolders) { Build-Index $sf.FullName }

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("<!-- GENERATED by phaneslight doc-index. Do not hand-edit. -->")
  $lines.Add("# Index: $name")
  $lines.Add("")

  foreach ($sf in ($subfolders | Sort-Object Name)) {
    # An excluded subtree never gets an _index.md (the Test-Excluded guard above skips its
    # own Build-Index call entirely), so linking to one here would point at a file that can
    # never exist. Apply the same test the generation path uses.
    if (Test-Excluded $sf.FullName) { continue }
    $lines.Add("- $($sf.Name)/ : subfolder (see $($sf.Name)/_index.md)")
  }

  # Ordered by FILENAME, ordinal, descending (v3.6.1). The old key was LastWriteTime, which broke
  # the index in the two ways an index must not break. It could not answer "which is the latest",
  # the question a sequenced folder exists to answer: an index tail read SS00099 while SS00115 was
  # on disk, because the numbering is the sequence and mtime is not. And it made every index
  # position a function of when a file was last touched, so editing one old document reordered the
  # whole file and produced a diff of pure noise. A filename key is stable under edits and puts
  # zero-padded sequences (SS00116 > SS00115) and ISO date prefixes (2026-09-03_x) newest-first for
  # free. KNOWN LIMIT: unpadded numbers sort lexicographically (file10 before file2); pad them.
  #
  # Ordinal, not Sort-Object's culture-aware default, and reached through Array.Sort because
  # Sort-Object has no comparer parameter on 5.1. This is what makes the ordering byte-identical
  # to the POSIX sibling's `LC_ALL=C sort -r`.
  $names = [string[]]@($mdFiles | ForEach-Object { $_.Name })
  [System.Array]::Sort($names, [System.StringComparer]::Ordinal)
  [System.Array]::Reverse($names)
  # Ordinal-keyed: PowerShell's literal @{} is case-INSENSITIVE, which would collide two files
  # whose names differ only in case and drop one from the index entirely.
  $byName = New-Object System.Collections.Hashtable ([System.StringComparer]::Ordinal)
  foreach ($f in $mdFiles) { $byName[$f.Name] = $f }
  $entries = @($names | ForEach-Object { $byName[$_] })
  if ($entries.Count -le $INLINE) {
    foreach ($f in $entries) {
      $lines.Add("- $($f.Name) : $(Get-DocLine $f.FullName)")
    }
  } else {
    $newestSlice = $entries[0..($INLINE - 1)]
    $older = $entries[$INLINE..($entries.Count - 1)]
    foreach ($f in $newestSlice) {
      $lines.Add("- $($f.Name) : $(Get-DocLine $f.FullName)")
    }
    $lines.Add("- ... $($older.Count) older entries collapsed into _index_archive.md")
    $arch = New-Object System.Collections.Generic.List[string]
    $arch.Add("<!-- GENERATED by phaneslight doc-index. Frozen overflow of _index.md. -->")
    $arch.Add("# Index archive: $name")
    $arch.Add("")
    foreach ($f in $older) {
      $arch.Add("- $($f.Name) : $(Get-DocLine $f.FullName)")
    }
    # Advisory: a read-only or locked index must not abort the walk under EAP = 'Stop'.
    try { Write-Utf8 (Join-Path $folder '_index_archive.md') (($arch -join "`n") + "`n") }
    catch { [Console]::Error.WriteLine("doc-index: cannot write _index_archive.md in $folder, skipping") }
  }

  try { Write-Utf8 (Join-Path $folder '_index.md') (($lines -join "`n") + "`n") }
  catch {
    [Console]::Error.WriteLine("doc-index: cannot write _index.md in $folder, skipping")
    return
  }
  $script:written++
}

Build-Index $docPath
Write-Output "doc-index: regenerated $written index file(s)"
exit 0
