-- =====================================================================
-- AFLDB 003 — Matches
-- =====================================================================

-- Round modelling: the legacy round column is text ('1'..'25', 'EF',
-- 'QF', 'SF', 'PF', 'GF'). Finals are not numbered, so round_number is
-- NULL for them and round_type carries the meaning.
CREATE TYPE round_type AS ENUM (
  'home_and_away',
  'elimination_final',
  'qualifying_final',
  'semi_final',
  'preliminary_final',
  'grand_final'
);

CREATE TYPE match_result AS ENUM ('home_win', 'away_win', 'draw');

CREATE TABLE matches (
  id               integer  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  legacy_match_id  integer  UNIQUE,
  -- Stable natural key: season|round|date|home|away
  match_key        text     NOT NULL UNIQUE,

  season           smallint NOT NULL REFERENCES seasons(year),
  round_code       text     NOT NULL,
  round_number     smallint,
  round_type       round_type NOT NULL,
  is_final         boolean  NOT NULL,

  match_date       date     NOT NULL,
  match_time       text,
  scheduled_at     timestamptz,

  -- Venue canonicalisation is a later enrichment pass, so venue_id is
  -- nullable while venue_raw is always populated.
  venue_id         integer  REFERENCES venues(id),
  venue_raw        text     NOT NULL,

  home_club_id     integer  NOT NULL REFERENCES clubs(id),
  away_club_id     integer  NOT NULL REFERENCES clubs(id),

  home_goals       smallint,
  home_behinds     smallint,
  home_score       smallint NOT NULL,
  away_goals       smallint,
  away_behinds     smallint,
  away_score       smallint NOT NULL,

  result           match_result NOT NULL,
  winner_club_id   integer  REFERENCES clubs(id),   -- NULL on a draw
  margin           smallint NOT NULL,

  -- NULL means attendance was not recorded (1,651 matches), not zero.
  attendance       integer,

  match_event      text,
  notes            text,

  CONSTRAINT matches_clubs_differ_ck CHECK (home_club_id <> away_club_id),
  CONSTRAINT matches_margin_ck       CHECK (margin = abs(home_score - away_score)),
  CONSTRAINT matches_winner_ck       CHECK (
    (result = 'draw'     AND winner_club_id IS NULL) OR
    (result = 'home_win' AND winner_club_id = home_club_id) OR
    (result = 'away_win' AND winner_club_id = away_club_id)),
  CONSTRAINT matches_round_number_ck CHECK (
    (round_type = 'home_and_away' AND round_number IS NOT NULL) OR
    (round_type <> 'home_and_away' AND round_number IS NULL)),
  CONSTRAINT matches_is_final_ck     CHECK (is_final = (round_type <> 'home_and_away')),
  CONSTRAINT matches_attendance_ck   CHECK (attendance IS NULL OR attendance >= 0)
);
COMMENT ON COLUMN matches.attendance IS
  'NULL means not recorded (1,651 matches, mostly early-era and 2020). Never defaulted to 0.';
COMMENT ON COLUMN matches.venue_id IS
  'Nullable by design: venue canonicalisation is an enrichment pass. venue_raw is authoritative until then.';

CREATE INDEX ix_matches_season_round ON matches (season, round_number);
CREATE INDEX ix_matches_date         ON matches (match_date);
CREATE INDEX ix_matches_home         ON matches (home_club_id, season);
CREATE INDEX ix_matches_away         ON matches (away_club_id, season);
CREATE INDEX ix_matches_venue        ON matches (venue_id) WHERE venue_id IS NOT NULL;
CREATE INDEX ix_matches_finals       ON matches (season, round_type) WHERE is_final;
CREATE INDEX ix_matches_winner       ON matches (winner_club_id) WHERE winner_club_id IS NOT NULL;

-- Quarter-by-quarter scores ------------------------------------------
-- Normalised rather than 24 wide columns: supports extra periods and
-- keeps "not recorded" expressible per period.
CREATE TABLE match_period_scores (
  match_id  integer  NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  club_id   integer  NOT NULL REFERENCES clubs(id),
  period    smallint NOT NULL,
  goals     smallint,
  behinds   smallint,
  points    smallint,
  PRIMARY KEY (match_id, club_id, period),
  CONSTRAINT match_period_ck CHECK (period BETWEEN 1 AND 8)
);
COMMENT ON TABLE match_period_scores IS
  'Cumulative-to-date scores per period per club, as published. Periods 1-4 are quarters.';
