-- =====================================================================
-- AFLDB 017 — Club organizations versus historical identities
-- =====================================================================
-- AFLDB has always had 24 club identities. What it lacked was a name for
-- the thing that persists across a rename: the organization.
--
--   24 historical identities   time-bounded, each with its own name,
--                              slug and era. Matches, player stints and
--                              ladder rows attach here.
--   21 organizations           the continuing entity. "Clubs played",
--                              lineage totals and club navigation
--                              attach here.
--
-- Three organizations carry two identities each:
--   South Melbourne (1897-1981) -> Sydney (1982-)
--   Footscray (1925-1996)       -> Western Bulldogs (1997-)
--   North Melbourne (1925-)     -> Kangaroos (1999-2007) -> North Melbourne
--
-- Fitzroy, Brisbane Bears and University stay SEPARATE organizations.
-- Fitzroy and the Bears combined into Brisbane Lions in 1997, but a
-- merger is not a rename: Fitzroy's 100 seasons are Fitzroy's, and
-- folding them into the Lions' record would invent a history the club
-- never had. The relationship is recorded explicitly instead, so the
-- link is navigable without the statistics being combined.
--
-- The 24-row clubs table is kept as the identity layer, so no existing
-- foreign key moves.
-- =====================================================================

-- --------------------------------------------------------------------
-- 1. Organizations
-- --------------------------------------------------------------------
CREATE TABLE club_organizations (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          text    NOT NULL UNIQUE,
  slug          text    NOT NULL UNIQUE,
  first_season  smallint REFERENCES seasons(year),
  last_season   smallint REFERENCES seasons(year),
  is_active     boolean NOT NULL DEFAULT true,
  notes         text
);
COMMENT ON TABLE club_organizations IS
  'The continuing club. Spans every historical identity the club has traded under. 21 rows against 24 identities.';
COMMENT ON COLUMN club_organizations.first_season IS
  'Earliest season of any identity in this lineage: 1897 for the Sydney organization, via South Melbourne.';

-- Seed from the identities that are their own current identity. That
-- column already encodes the lineage; this migration only gives it a
-- table of its own.
INSERT INTO club_organizations (id, name, slug, first_season, last_season, is_active)
SELECT cur.id,
       cur.name,
       cur.slug,
       min(mem.first_season),
       max(mem.last_season),
       max(mem.last_season) = (SELECT max(year) FROM seasons)
FROM clubs cur
JOIN clubs mem ON mem.current_identity_id = cur.id
WHERE cur.id = cur.current_identity_id
GROUP BY cur.id, cur.name, cur.slug;

SELECT setval(pg_get_serial_sequence('club_organizations', 'id'),
              (SELECT max(id) FROM club_organizations));

-- --------------------------------------------------------------------
-- 2. Identity -> organization
-- --------------------------------------------------------------------
ALTER TABLE clubs
  ADD COLUMN organization_id integer REFERENCES club_organizations(id);

UPDATE clubs SET organization_id = current_identity_id;

ALTER TABLE clubs ALTER COLUMN organization_id SET NOT NULL;

COMMENT ON COLUMN clubs.organization_id IS
  'The continuing club this identity belongs to. Use for "clubs played" and lineage totals; use clubs.id for matches, stints and era pages.';
COMMENT ON COLUMN clubs.current_identity_id IS
  'Retained for compatibility. organization_id is the same lineage expressed as a first-class entity.';

CREATE INDEX ix_clubs_organization ON clubs (organization_id, first_season);

-- Every organization must have at least one identity, and an identity
-- cannot belong to an organization that does not exist.
ALTER TABLE clubs
  ADD CONSTRAINT clubs_org_span_ck
  CHECK (first_season IS NULL OR last_season IS NULL OR first_season <= last_season);

-- --------------------------------------------------------------------
-- 3. Relationships between organizations
-- --------------------------------------------------------------------
-- A merger, unlike a rename, does not transfer history.
CREATE TYPE organization_relation AS ENUM (
  'merged_into',   -- two clubs combined to form a third; records do NOT transfer
  'relocated_to',  -- same club, new city (recorded as a rename in practice)
  'folded'         -- ceased, no successor
);

CREATE TABLE club_organization_relations (
  from_organization_id integer NOT NULL REFERENCES club_organizations(id),
  to_organization_id   integer REFERENCES club_organizations(id),
  relation             organization_relation NOT NULL,
  effective_season     smallint REFERENCES seasons(year),
  notes                text,
  PRIMARY KEY (from_organization_id, relation),
  CONSTRAINT cor_target_ck CHECK (
    (relation = 'folded' AND to_organization_id IS NULL)
    OR (relation <> 'folded' AND to_organization_id IS NOT NULL)
  ),
  CONSTRAINT cor_not_self_ck CHECK (from_organization_id <> to_organization_id)
);
COMMENT ON TABLE club_organization_relations IS
  'Navigable links between organizations. Deliberately does NOT combine statistics: Fitzroy''s record stays Fitzroy''s.';

INSERT INTO club_organization_relations
      (from_organization_id, to_organization_id, relation, effective_season, notes)
SELECT f.id, l.id, 'merged_into', 1997,
       'Fitzroy and Brisbane Bears combined to form Brisbane Lions in 1997. Statistics are not combined: each organization keeps its own record.'
  FROM club_organizations f, club_organizations l
 WHERE f.slug = 'fitzroy' AND l.slug = 'brisbane-lions';

INSERT INTO club_organization_relations
      (from_organization_id, to_organization_id, relation, effective_season, notes)
SELECT b.id, l.id, 'merged_into', 1997,
       'Brisbane Bears and Fitzroy combined to form Brisbane Lions in 1997. Statistics are not combined.'
  FROM club_organizations b, club_organizations l
 WHERE b.slug = 'brisbane-bears' AND l.slug = 'brisbane-lions';

INSERT INTO club_organization_relations
      (from_organization_id, to_organization_id, relation, effective_season, notes)
SELECT u.id, NULL, 'folded', 1915,
       'University withdrew from the competition after the 1914 season and never returned.'
  FROM club_organizations u WHERE u.slug = 'university';

-- --------------------------------------------------------------------
-- 4. Resolving a season to the identity that was active in it
-- --------------------------------------------------------------------
-- club_seasons was built from the source ladder, which uses only modern
-- club names. That gave Sydney ladder rows back to 1897 and Footscray
-- none at all, while their player leaders came from the historical
-- identities — a club page that disagreed with itself.
CREATE FUNCTION afldb_identity_for_season(p_organization_id integer, p_season smallint)
RETURNS integer
LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT c.id
    FROM clubs c
   WHERE c.organization_id = p_organization_id
     AND p_season >= COALESCE(c.first_season, p_season)
     AND p_season <= COALESCE(c.last_season, p_season)
   -- Kangaroos (1999-2007) sits inside North Melbourne's span, so the
   -- narrower, later-starting identity must win.
   ORDER BY c.first_season DESC NULLS LAST
   LIMIT 1;
$$;
COMMENT ON FUNCTION afldb_identity_for_season IS
  'The club identity trading in a given season. Ladder rows and season pages resolve through this so a club is named as it was at the time.';

GRANT SELECT ON club_organizations, club_organization_relations TO afldb_app;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON club_organizations, club_organization_relations TO afldb_import;
GRANT USAGE, SELECT ON SEQUENCE club_organizations_id_seq TO afldb_import;
