-- =====================================================================
-- AFLDB 019 — Draft people, separate from draft rows
-- =====================================================================
-- The draft source has 6,810 rows describing 5,057 people. A person can
-- appear several times: drafted, delisted, re-drafted, traded, signed as
-- a free agent. Matching each ROW to an AFLDB player independently means
-- the same person can be linked in one row and unlinked in the next.
--
-- So identity is resolved once per PERSON, keyed on DraftGuru's own
-- person id, and propagated to that person's rows.
--
-- Two different judgements are kept apart, because conflating them is
-- what makes "1,664 unmatched" look like one homogeneous defect:
--
--   PERSON LINK CONFIDENCE   is this draft person the same human as this
--                            AFLDB player?
--   ROW PLAUSIBILITY         does this row's own content hang together?
--
-- The 1,664 unmatched rows are two quite different populations:
--
--   1,555 rows report zero senior games. These people were drafted and
--         never played. Having NO AFLDB player is the CORRECT outcome —
--         AFLDB only contains players who appeared. They are not a
--         backlog and must not be "fixed".
--
--     109 rows across 85 people report senior games. These are a real
--         matching backlog: the person played, so an AFLDB player should
--         exist. Flagged for work rather than silently left.
--
-- Nothing here matches fuzzily. A name-similarity score is a candidate,
-- never a link. Automatic linking is restricted to states the source
-- itself considers certain, and the CHECK constraints below make an
-- unevidenced link impossible to store.
-- =====================================================================

CREATE TABLE draft_persons (
  id               integer  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_id        smallint NOT NULL REFERENCES sources(id),

  -- The durable external identity. Names change spelling between rows
  -- (Brad/Bradley Hill, Nathan/Nat Fyfe); these do not.
  dg_person_id     integer  NOT NULL,
  player_url       text     NOT NULL,

  -- Always retained, whether or not the person links to a player.
  display_name_raw text     NOT NULL,
  name_key         text     NOT NULL,

  player_id        integer  REFERENCES players(id),
  link_status      link_status NOT NULL,
  candidate_count  smallint NOT NULL DEFAULT 0,
  match_method     text,
  confidence_notes text,

  -- As reported by the draft source, NOT by AFLDB. Kept to tell the two
  -- unmatched populations apart; never used as a career statistic.
  reported_games   integer,
  reported_goals   integer,

  -- True when the person played senior football but has no AFLDB player.
  -- This is the actual backlog; zero-game draftees are not in it.
  is_matching_backlog boolean NOT NULL DEFAULT false,

  UNIQUE (source_id, dg_person_id),

  -- A trusted link must actually point at a player. This is the
  -- structural guarantee that "unique" can never mean "unlinked".
  CONSTRAINT draft_persons_link_ck CHECK (
    (link_status IN ('unique', 'resolved') AND player_id IS NOT NULL)
    OR (link_status IN ('ambiguous', 'unmatched', 'implausible') AND player_id IS NULL)
  ),
  -- A backlog entry is by definition unlinked and did play.
  CONSTRAINT draft_persons_backlog_ck CHECK (
    NOT is_matching_backlog
    OR (player_id IS NULL AND COALESCE(reported_games, 0) > 0)
  )
);
COMMENT ON TABLE draft_persons IS
  'One row per person in the draft source, keyed on the source''s own person id. Identity is resolved here once and propagated to draft_picks, so a person cannot be linked in one row and unlinked in another.';
COMMENT ON COLUMN draft_persons.reported_games IS
  'Senior games as the DRAFT source reports them. Used only to tell a genuine non-player from a matching backlog; never displayed as a career total.';
COMMENT ON COLUMN draft_persons.is_matching_backlog IS
  'The person played senior football but is not linked to an AFLDB player. 1,555 zero-game draftees are correctly unlinked and are NOT flagged here.';

CREATE INDEX ix_draft_persons_player  ON draft_persons (player_id)
  WHERE player_id IS NOT NULL;
CREATE INDEX ix_draft_persons_backlog ON draft_persons (dg_person_id)
  WHERE is_matching_backlog;
CREATE INDEX ix_draft_persons_name    ON draft_persons (name_key);

-- --------------------------------------------------------------------
-- Draft rows point at the person
-- --------------------------------------------------------------------
ALTER TABLE draft_picks
  ADD COLUMN draft_person_id integer REFERENCES draft_persons(id),
  ADD COLUMN dg_person_id    integer,
  ADD COLUMN player_url      text,
  ADD COLUMN reported_games  integer,
  ADD COLUMN reported_goals  integer;

COMMENT ON COLUMN draft_picks.draft_person_id IS
  'The person this row describes. Identity lives on draft_persons; this row keeps only what is specific to the transaction.';
COMMENT ON COLUMN draft_picks.player_name_raw IS
  'The name exactly as the source printed it, retained for every row whether linked or not.';

CREATE INDEX ix_draft_picks_person ON draft_picks (draft_person_id);

-- Same guarantee at row grain.
ALTER TABLE draft_picks
  ADD CONSTRAINT draft_picks_link_ck CHECK (
    (link_status_value IN ('unique', 'resolved') AND player_id IS NOT NULL)
    OR (link_status_value IN ('ambiguous', 'unmatched', 'implausible') AND player_id IS NULL)
  );

GRANT SELECT ON draft_persons TO afldb_app;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON draft_persons TO afldb_import;
GRANT USAGE, SELECT ON SEQUENCE draft_persons_id_seq TO afldb_import;
