-- =====================================================================
-- AFLDB 040 — Password reset: a temporary password, changed on first use
-- =====================================================================
-- Until now the only way to give an administrator a working password was
-- to re-issue an INVITE, and accepting one resets the TOTP secret as well
-- (see migration 030 and src/app/admin/invite/[token]/actions.ts). That
-- makes "I have forgotten my password" cost the authenticator too: the
-- person has to delete the entry from their phone and scan a new QR code
-- for a factor that never went wrong.
--
-- So: a super admin (or a delegated admin manager, under the same rank
-- rules the invite flow already applies) sets a TEMPORARY password. It is
-- generated by the server, shown to the issuing admin exactly once, and
-- carries an obligation to change it, which is what this migration adds.
--
--   must_change_password   the obligation. Every admin page honours it by
--                          redirecting to /admin/password until it clears,
--                          so a temporary password grants exactly one
--                          ability: replacing itself. It is NOT merely a
--                          prompt on the login form — a prompt is skipped
--                          by typing another URL.
--
--   password_changed_at    when the password last changed, and by
--                          implication how long a temporary one has been
--                          outstanding. /admin/admins shows it, which is
--                          the only way anyone notices a reset that was
--                          issued and never used.
--
-- The temporary password itself is stored the same way every other one is
-- — scrypt, via hashPassword() — and nowhere else. Nothing here holds
-- plaintext, and the value shown once to the issuing admin is not
-- recoverable afterwards; a lost one is re-issued, not looked up.
--
-- The authenticator is deliberately untouched by this flow. Resetting the
-- password is not evidence that the second factor is compromised, and a
-- password reset that quietly disarmed 2FA would make this the weakest
-- door in the building. Losing the authenticator remains the invite
-- flow's job, which re-enrols both factors together and proves the new
-- one with a live code before the account is written.
-- =====================================================================

ALTER TABLE auth_users
  ADD COLUMN must_change_password boolean     NOT NULL DEFAULT false,
  ADD COLUMN password_changed_at  timestamptz;

COMMENT ON COLUMN auth_users.must_change_password IS
  'Set when an admin issues a temporary password. While true the account may '
  'reach /admin/password and nothing else — requireUploader() in '
  'src/lib/auth/session.ts enforces it on every admin route, not just at login.';

COMMENT ON COLUMN auth_users.password_changed_at IS
  'When password_hash was last written, by any path: invite acceptance, an '
  'admin-issued temporary password, or the holder changing their own. NULL for '
  'accounts created before migration 040.';

-- Existing rows: the password was set at some point before now, and
-- pretending to know when would be worse than admitting we do not.
-- NULL reads as "before this was recorded" on /admin/admins.

-- afldb_auth holds table-level SELECT/INSERT/UPDATE on auth_users from
-- migration 023, so the new columns are covered without a further grant.
-- afldb_app holds nothing on this table (031, and 039 made that the
-- default), which is what keeps a public page from reading the flag.
