/**
 * AFLDB-ISSUE-164 P1c — build a frozen draft label set from a person-page
 * snapshot.
 *
 *   npm run match:draft-labels -- <person_profile.jsonl> --out <labels.json>
 *                                 [--label-set <name>] [--zero-game-cohort <tag>]
 *
 * Offline. No database, no network, no environment. It reads the parsed
 * output of a Stage B1-style person-page acquisition
 * (`tools/rebuild/draftguru/profile_person_pages.py`) and writes a label
 * file the backtest's `--labels` mode consumes.
 *
 * Why this snapshot is admissible here
 * ------------------------------------
 * ISSUE-093 §21 admits the Stage B1 person snapshot as a **profiling and
 * validation oracle only, never an import source**. Evaluating a matcher
 * against it is exactly that admitted use: nothing here writes a link, and
 * the output is measurement truth, not identity data. Promoting the same
 * pairs into real links is Stage B3's separate, approved `--bridge` path
 * (`tools/rebuild/draftguru/import_draftguru.py`), and this tool is not it.
 *
 * What it refuses to guess
 * ------------------------
 * A missing AFL Tables href is not by itself a negative. For a person who
 * played senior football it means the bridge saw nothing, and calling that
 * "no AFLDB player" would invent a true negative out of an absent
 * observation. A negative is emitted only when the page exposes no
 * identity AND the person sits in a declared zero-senior-game cohort;
 * everyone else with no href is reported as UNLABELLED and left out.
 *
 * Ambiguity is likewise a finding: a page carrying two distinct AFL Tables
 * identities is skipped, named, and never resolved by choosing one.
 */
import { readFileSync, writeFileSync } from 'node:fs';

import {
  LABEL_SET_SCHEMA_VERSION,
  normaliseAfltablesIdentity,
  parseLabelSet,
  type RawLabel,
} from './label-set';

type PersonProfileRecord = {
  player_url: string;
  primary_cohort?: string | null;
  terminal_classification?: string | null;
  afltables_identity?: string | null;
  afltables_identity_reason?: string | null;
  distinct_afltables_identity_count?: number | null;
};

function valueFor(argv: string[], flag: string): string | null {
  const index = argv.indexOf(flag);
  return index >= 0 ? argv[index + 1] ?? null : null;
}

function readJsonl(path: string): PersonProfileRecord[] {
  return readFileSync(path, 'utf8')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as PersonProfileRecord);
}

function main(): void {
  const argv = process.argv.slice(2);
  const inputPath = argv.find((a) => !a.startsWith('--')) ?? null;
  const outPath = valueFor(argv, '--out');
  const setName = valueFor(argv, '--label-set') ?? 'draft-person-page-bridge';
  const zeroGameCohort = valueFor(argv, '--zero-game-cohort') ?? 'zero_game_control';

  if (!inputPath || !outPath) {
    throw new Error(
      'usage: match:draft-labels -- <person_profile.jsonl> --out <labels.json> '
      + '[--label-set <name>] [--zero-game-cohort <tag>]',
    );
  }

  const records = readJsonl(inputPath);
  const labels: RawLabel[] = [];
  const skipped: Array<{ playerUrl: string; why: string }> = [];

  for (const record of records) {
    if (record.terminal_classification !== 'fetched') {
      skipped.push({ playerUrl: record.player_url, why: 'page was not fetched' });
      continue;
    }
    if ((record.distinct_afltables_identity_count ?? 0) > 1) {
      skipped.push({
        playerUrl: record.player_url,
        why: `${record.distinct_afltables_identity_count} distinct AFL Tables identities on one page`,
      });
      continue;
    }
    if (record.afltables_identity) {
      labels.push({
        player_url: record.player_url,
        expect: 'linked',
        afltables_external_id: normaliseAfltablesIdentity(record.afltables_identity),
        provenance: 'draftguru_person_page_afltables_bridge',
        note: record.primary_cohort ?? null,
      });
      continue;
    }
    if (record.primary_cohort === zeroGameCohort) {
      labels.push({
        player_url: record.player_url,
        expect: 'unlinked',
        afltables_external_id: null,
        provenance: 'zero_game_no_bridge',
        note: record.afltables_identity_reason ?? null,
      });
      continue;
    }
    skipped.push({
      playerUrl: record.player_url,
      why: record.afltables_identity_reason ?? 'no AFL Tables identity observed',
    });
  }

  const payload = {
    $comment:
      'AFLDB-ISSUE-164 P1c draft evaluation labels. Measurement truth only: no row here is a '
      + 'link, and nothing in this file may be imported. Generated by '
      + 'tools/matching/export-draft-labels.ts from a Stage B1-style person-page snapshot, '
      + 'which ISSUE-093 §21 admits as a profiling/validation oracle.',
    schema_version: LABEL_SET_SCHEMA_VERSION,
    source_key: 'draftguru',
    label_set: setName,
    input: inputPath,
    labels: labels.sort((a, b) => (a.player_url < b.player_url ? -1 : 1)),
    unlabelled: skipped.sort((a, b) => (a.playerUrl < b.playerUrl ? -1 : 1)),
  };

  // Validate what we just wrote with the same parser the backtest uses, so a
  // contradiction or a duplicate is a failure here rather than a surprise in
  // the middle of a measurement run.
  const parsed = parseLabelSet(payload);

  writeFileSync(outPath, JSON.stringify(payload, null, 2), 'utf8');

  console.log(`records read      ${records.length}`);
  console.log(`labels written    ${parsed.labels.length}`);
  console.log(`  linked          ${parsed.labels.filter((l) => l.expect === 'linked').length}`);
  console.log(`  unlinked        ${parsed.labels.filter((l) => l.expect === 'unlinked').length}`);
  console.log(`unlabelled        ${skipped.length}`);
  for (const s of skipped) console.log(`  ${s.playerUrl}  (${s.why})`);
  console.log(`written to        ${outPath}`);
}

main();
