<#
.SYNOPSIS
  AFLDB-ISSUE-155 SS27.27 -- disposable browser-acceptance fixture CREATE.

.DESCRIPTION
  afldb_test ONLY. Never touches afldb_dev or production, never edits .env.

  Seeds the two reserved Brownlow fixture seasons from
  tests/integration/brownlow-fixture.ts (2089 main, 2085 short-lineup) and
  three disposable auth accounts:
    issue155-acceptance-super@example.test        (super_admin)
    issue155-acceptance-admin@example.test        (admin)
    issue155-acceptance-contributor@example.test  (contributor)

  This is a standalone script FILE, not something meant to be pasted into an
  interactive shell in chunks -- that is exactly what was breaking the
  if/else parsing before. Run it as:

    powershell -ExecutionPolicy Bypass -File .\tools\admin\issue155-acceptance-create.ps1

  TOTP secrets are CREDENTIALS. They are printed to this terminal once, for
  immediate authenticator enrolment, and nowhere else -- never to a file,
  never redirected, never included in any SS27.27 evidence or screenshot.
  The password you type is never echoed or printed by this script.

.NOTES
  data_edits.table_name is an allowlist (migrations 057/058/094): 'players',
  'matches', 'draft_picks', 'award_winners', 'hall_of_fame',
  'honour_team_members', 'brownlow_vote_entry_state',
  'brownlow_season_authority'. There is NO 'player_match_stats' entry -- a
  Match Sheet save always audits as table_name='matches', row_id=<matchId>
  (src/db/queries/match-sheet.ts), which the fixture's own matchIds set
  already covers. The embedded fixture runner deletes data_edits ONLY by
  proven (table_name, row_id) membership in the fixture's own id sets --
  never broadly by admin_user_id -- and separately counts every other FK
  into auth_users so an edit against something outside the fixture closure
  is refused and named, never silently dropped or rewritten.
#>

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
Set-Location $repoRoot

# --- 1. Load AFLDB_TEST_DATABASE_URL from .env, robust to CRLF and quoting ---

$envPath = Join-Path $repoRoot '.env'
if (-not (Test-Path $envPath)) {
    Write-Error "Refusing: .env not found at $envPath"
    exit 1
}

$rawEnv = Get-Content -Path $envPath -Raw
$envLines = $rawEnv -split "`r?`n"
$testDsnLine = $envLines | Where-Object { $_ -match '^\s*AFLDB_TEST_DATABASE_URL\s*=' } | Select-Object -First 1
if (-not $testDsnLine) {
    Write-Error "Refusing: AFLDB_TEST_DATABASE_URL not found in .env"
    exit 1
}

$testDsn = $testDsnLine -replace '^\s*AFLDB_TEST_DATABASE_URL\s*=\s*', ''
$testDsn = $testDsn.Trim()
$testDsn = $testDsn -replace '^"(.*)"$', '$1'
$testDsn = $testDsn -replace "^'(.*)'$", '$1'
$testDsn = $testDsn.TrimEnd("`r").Trim()

# --- 2. Hard guard BEFORE any process env is touched or any connection opened ---

if ($testDsn -notmatch '/afldb_test(\?|$)') {
    Write-Error "Refusing: AFLDB_TEST_DATABASE_URL does not name afldb_test: $testDsn"
    exit 1
}

Write-Host "Guard OK: AFLDB_TEST_DATABASE_URL names afldb_test." -ForegroundColor Green

# --- 3. Preserve every env var this script is about to change ---

$originalDatabaseUrl = $env:DATABASE_URL
$originalTestDatabaseUrl = $env:AFLDB_TEST_DATABASE_URL
$originalNodeOptions = $env:NODE_OPTIONS
$originalFixturePassword = $env:AFLDB_FIXTURE_PASSWORD

$scriptPath = Join-Path $repoRoot 'tools\admin\issue155-acceptance-fixtures.ts'

try {
    # Mirrors tests/setup.ts's own redirection of DATABASE_URL for test runs,
    # so @/db/client (imported at module load time by the fixture runner)
    # picks up afldb_test before its connection pool is created.
    $env:DATABASE_URL = $testDsn
    $env:AFLDB_TEST_DATABASE_URL = $testDsn
    $env:NODE_OPTIONS = ("$originalNodeOptions --conditions=react-server").Trim()

    # --- 4. Write the temporary fixture runner ---

    @'
#!/usr/bin/env tsx
/**
 * AFLDB-ISSUE-155 SS27.27 -- disposable browser-acceptance fixtures.
 * Generated by issue155-acceptance-create.ps1 / issue155-acceptance-cleanup.ps1.
 * afldb_test ONLY.
 *
 * Usage:
 *   create:  npx tsx tools/admin/issue155-acceptance-fixtures.ts create
 *   cleanup: npx tsx tools/admin/issue155-acceptance-fixtures.ts cleanup
 */
import { sql } from '@/db/client';
import {
  BROWNLOW_MAIN_SEASON,
  BROWNLOW_SHORT_SEASON,
  seedBrownlowSeason,
} from '../../tests/integration/brownlow-fixture';
import { generateTotpSecret, hashPassword, MIN_PASSWORD_LENGTH, totpUri } from '../../src/lib/auth/crypto';

const FIXTURE_EMAILS: Record<'super_admin' | 'admin' | 'contributor', string> = {
  super_admin: 'issue155-acceptance-super@example.test',
  admin: 'issue155-acceptance-admin@example.test',
  contributor: 'issue155-acceptance-contributor@example.test',
};

async function assertAfldbTest(): Promise<void> {
  const dsn = process.env.DATABASE_URL ?? '';
  if (!/\/afldb_test(\?|$)/.test(dsn)) {
    console.error('Refusing: DATABASE_URL does not name afldb_test.');
    process.exit(1);
  }
  const [row] = await sql<{ db: string }[]>`SELECT current_database() AS db`;
  if (row.db !== 'afldb_test') {
    console.error(`Refusing: connected database is "${row.db}", not afldb_test.`);
    process.exit(1);
  }
  console.log(`Guard OK: current_database() = ${row.db}`);
}

/**
 * Ordered removal of disposable Brownlow rows for the given fixture seasons
 * only. Builds the fixture's own match id / player id sets explicitly BEFORE
 * any destructive delete, and uses them to scope every data_edits delete by
 * proven (table_name, row_id) membership -- the only two table_name values
 * a Brownlow/Match Sheet acceptance flow can write against fixture matches
 * are 'matches' and 'brownlow_vote_entry_state', both keyed by match_id;
 * 'brownlow_season_authority' is keyed by season; 'players' is included
 * defensively in case a fixture player's own row was edited via the data
 * editor during acceptance.
 */
async function removeFixtureBrownlowData(seasons: number[]): Promise<void> {
  for (const season of seasons) {
    const prefix = `issue155-${season}-`;

    const matchRows = await sql<{ id: number }[]>`
      SELECT id::int AS id FROM matches WHERE match_key LIKE ${`${prefix}%`}
    `;
    const matchIds = matchRows.map((r) => r.id);

    const playerRows = await sql<{ id: number }[]>`
      SELECT id::int AS id FROM players WHERE slug LIKE ${`${prefix}%`}
    `;
    const playerIds = playerRows.map((r) => r.id);

    if (matchIds.length > 0) {
      await sql`DELETE FROM data_edits WHERE table_name = 'matches' AND row_id = ANY(${matchIds})`;
      await sql`DELETE FROM data_edits WHERE table_name = 'brownlow_vote_entry_state' AND row_id = ANY(${matchIds})`;
      await sql`DELETE FROM brownlow_vote_entry_state WHERE match_id = ANY(${matchIds})`;
    }
    await sql`DELETE FROM data_edits WHERE table_name = 'brownlow_season_authority' AND row_id = ${season}`;
    await sql`DELETE FROM brownlow_season_authority WHERE season = ${season}`;
    await sql`DELETE FROM brownlow_round_votes WHERE season = ${season}`;
    await sql`DELETE FROM brownlow_season_votes WHERE season = ${season}`;

    if (playerIds.length > 0) {
      await sql`DELETE FROM data_edits WHERE table_name = 'players' AND row_id = ANY(${playerIds})`;
      await sql`DELETE FROM player_match_stats WHERE player_id = ANY(${playerIds})`;
      await sql`DELETE FROM player_career_stats WHERE player_id = ANY(${playerIds})`;
      await sql`DELETE FROM player_season_stats WHERE player_id = ANY(${playerIds})`;
      await sql`DELETE FROM player_club_season_stats WHERE player_id = ANY(${playerIds})`;
      await sql`DELETE FROM player_clubs WHERE player_id = ANY(${playerIds})`;
      await sql`DELETE FROM players WHERE id = ANY(${playerIds})`;
    }
    await sql`DELETE FROM club_seasons WHERE season = ${season}`;
    await sql`DELETE FROM matches WHERE match_key LIKE ${`${prefix}%`}`;
    await sql`DELETE FROM stat_availability WHERE season = ${season}`;
    await sql`DELETE FROM seasons WHERE year = ${season}`;
    console.log(`Removed fixture Brownlow data for season ${season}: ${matchIds.length} match(es), ${playerIds.length} player(s).`);
  }
}

/**
 * Every FK into auth_users except auth_sessions (ON DELETE CASCADE) and
 * auth_audit_log (deleted separately as the disposable identity's own
 * history, not canonical provenance). data_edits.admin_user_id is included
 * here as a residual check ONLY -- by the time this runs, every fixture-
 * owned data_edits row has already been deleted by (table_name, row_id)
 * membership above, so any row still counted here belongs to something
 * OUTSIDE the fixture closure and must block deletion, named exactly.
 */
async function blockedAuthReferences(userIds: number[]): Promise<{ ref: string; n: number }[]> {
  if (userIds.length === 0) return [];
  const rows = await sql<{ ref: string; n: number }[]>`
    SELECT * FROM (
      SELECT 'beta_access_codes.created_by' AS ref, count(*)::int AS n FROM beta_access_codes WHERE created_by = ANY(${userIds})
      UNION ALL SELECT 'beta_allowed_emails.added_by', count(*)::int FROM beta_allowed_emails WHERE added_by = ANY(${userIds})
      UNION ALL SELECT 'data_submissions.uploaded_by', count(*)::int FROM data_submissions WHERE uploaded_by = ANY(${userIds})
      UNION ALL SELECT 'data_submissions.reviewed_by', count(*)::int FROM data_submissions WHERE reviewed_by = ANY(${userIds})
      UNION ALL SELECT 'admin_invites.invited_by', count(*)::int FROM admin_invites WHERE invited_by = ANY(${userIds})
      UNION ALL SELECT 'beta_join_requests.reviewed_by', count(*)::int FROM beta_join_requests WHERE reviewed_by = ANY(${userIds})
      UNION ALL SELECT 'site_settings.updated_by', count(*)::int FROM site_settings WHERE updated_by = ANY(${userIds})
      UNION ALL SELECT 'site_media.uploaded_by', count(*)::int FROM site_media WHERE uploaded_by = ANY(${userIds})
      UNION ALL SELECT 'nl_search_review.reviewed_by', count(*)::int FROM nl_search_review WHERE reviewed_by = ANY(${userIds})
      UNION ALL SELECT 'data_edits.admin_user_id', count(*)::int FROM data_edits WHERE admin_user_id = ANY(${userIds})
      UNION ALL SELECT 'player_link_suggestions.resolved_by', count(*)::int FROM player_link_suggestions WHERE resolved_by = ANY(${userIds})
      UNION ALL SELECT 'player_link_resolutions.admin_user_id', count(*)::int FROM player_link_resolutions WHERE admin_user_id = ANY(${userIds})
      UNION ALL SELECT 'data_overrides.admin_user_id', count(*)::int FROM data_overrides WHERE admin_user_id = ANY(${userIds})
      UNION ALL SELECT 'promotion_decisions.admin_user_id', count(*)::int FROM promotion_decisions WHERE admin_user_id = ANY(${userIds})
      UNION ALL SELECT 'brownlow_vote_entry_state.created_by', count(*)::int FROM brownlow_vote_entry_state WHERE created_by = ANY(${userIds})
      UNION ALL SELECT 'brownlow_vote_entry_state.updated_by', count(*)::int FROM brownlow_vote_entry_state WHERE updated_by = ANY(${userIds})
      UNION ALL SELECT 'brownlow_vote_entry_state.finalised_by', count(*)::int FROM brownlow_vote_entry_state WHERE finalised_by = ANY(${userIds})
      UNION ALL SELECT 'brownlow_season_authority.published_by', count(*)::int FROM brownlow_season_authority WHERE published_by = ANY(${userIds})
      UNION ALL SELECT 'brownlow_season_authority.updated_by', count(*)::int FROM brownlow_season_authority WHERE updated_by = ANY(${userIds})
    ) blocked WHERE n > 0
  `;
  return rows;
}

async function removeFixtureAuthUsers(emails: string[]): Promise<void> {
  if (emails.length === 0) return;
  const users = await sql<{ id: number; email: string }[]>`
    SELECT id, email FROM auth_users WHERE email = ANY(${emails})
  `;
  if (users.length === 0) {
    console.log('No matching fixture auth accounts found.');
    return;
  }
  const userIds = users.map((r) => r.id);
  const blocked = await blockedAuthReferences(userIds);
  if (blocked.length > 0) {
    const detail = blocked.map((b) => `${b.ref} (${b.n})`).join(', ');
    throw new Error(`Refusing to delete fixture auth accounts: still referenced by ${detail}.`);
  }
  await sql`DELETE FROM auth_audit_log WHERE actor_user_id = ANY(${userIds})`;
  await sql`DELETE FROM auth_sessions WHERE user_id = ANY(${userIds})`;
  await sql`DELETE FROM auth_users WHERE id = ANY(${userIds})`;
  console.log(`Removed ${users.length} fixture auth account(s): ${users.map((r) => r.email).join(', ')}`);
}

async function create(): Promise<void> {
  const password = process.env.AFLDB_FIXTURE_PASSWORD ?? '';
  if (password.length < MIN_PASSWORD_LENGTH) {
    console.error(`Refusing: set AFLDB_FIXTURE_PASSWORD (min ${MIN_PASSWORD_LENGTH} chars).`);
    process.exit(1);
  }
  await assertAfldbTest();

  const createdSeasons: number[] = [];
  const createdEmails: string[] = [];

  try {
    console.log(`Seeding season ${BROWNLOW_MAIN_SEASON} (main)...`);
    const main = await seedBrownlowSeason(BROWNLOW_MAIN_SEASON);
    createdSeasons.push(BROWNLOW_MAIN_SEASON);

    console.log(`Seeding season ${BROWNLOW_SHORT_SEASON} (short lineup)...`);
    const short = await seedBrownlowSeason(BROWNLOW_SHORT_SEASON);
    createdSeasons.push(BROWNLOW_SHORT_SEASON);

    const passwordHash = await hashPassword(password);
    for (const [role, email] of Object.entries(FIXTURE_EMAILS)) {
      const secret = generateTotpSecret();
      await sql`
        INSERT INTO auth_users (email, role, password_hash, totp_secret,
                                 must_change_password, password_changed_at, disabled_at)
        VALUES (${email}, ${role}, ${passwordHash}, ${secret}, false, now(), NULL)
        ON CONFLICT (email) DO UPDATE
          SET role = EXCLUDED.role, password_hash = EXCLUDED.password_hash,
              totp_secret = EXCLUDED.totp_secret, totp_last_step = NULL,
              must_change_password = false, password_changed_at = now(), disabled_at = NULL
      `;
      await sql`
        UPDATE auth_sessions SET revoked_at = now()
         WHERE user_id = (SELECT id FROM auth_users WHERE email = ${email}) AND revoked_at IS NULL
      `;
      createdEmails.push(email);
      console.log(`\n${role} ready: ${email}`);
      console.log('  ENROL THIS NOW (credential, shown once, terminal only):');
      console.log(`  TOTP secret : ${secret}`);
      console.log(`  otpauth URI : ${totpUri(secret, email)}`);
    }

    console.log('\n--- Fixture summary ---');
    console.log(`Main:  /admin/brownlow/${main.season}  matches: ${main.matches.map((m) => m.matchId).join(', ')}`
      + (main.wildcardFinalMatchId ? ` | wildcard final: ${main.wildcardFinalMatchId}` : '')
      + (main.grandFinalMatchId ? ` | grand final: ${main.grandFinalMatchId}` : ''));
    console.log(`Short: /admin/brownlow/${short.season}  matches: ${short.matches.map((m) => m.matchId).join(', ')}`
      + ' (second match has a short away lineup)');
    console.log('\nCREATE OK. Do not screenshot or log this terminal -- it carries one-time TOTP secrets.');
  } catch (error) {
    console.error('\nCREATE FAILED. Partial state before failure:');
    console.error(`  Seasons seeded: ${createdSeasons.length > 0 ? createdSeasons.join(', ') : '(none)'}`);
    console.error(`  Auth accounts created: ${createdEmails.length > 0 ? createdEmails.join(', ') : '(none)'}`);
    console.error('\nAttempting automatic rollback of exactly that partial state...');
    try {
      if (createdSeasons.length > 0) await removeFixtureBrownlowData(createdSeasons);
      if (createdEmails.length > 0) await removeFixtureAuthUsers(createdEmails);
      console.error('Rollback complete: afldb_test has no fixture residue from this failed run.');
    } catch (rollbackError) {
      console.error('ROLLBACK ALSO FAILED -- manual cleanup required. Rollback error:');
      console.error(rollbackError);
      console.error('Re-run this fixture runner with "cleanup" once the underlying issue above is resolved.');
    }
    console.error('\nOriginal CREATE error:');
    throw error;
  }
}

async function cleanup(): Promise<void> {
  await assertAfldbTest();
  await removeFixtureBrownlowData([BROWNLOW_MAIN_SEASON, BROWNLOW_SHORT_SEASON]);
  await removeFixtureAuthUsers(Object.values(FIXTURE_EMAILS));
}

/**
 * READ-ONLY. Reports whether any ISSUE-155 fixture residue already exists
 * for the given seasons -- a seasons row, any matches on the fixture's
 * match_key prefix, or any players on its slug prefix. Exit code only:
 * 0 = clean, 2 = residue found, never writes anything. Called by CREATE
 * before it ever prompts for a password, so a stale run from a previous
 * interrupted attempt is caught before any new work starts, and
 * seedBrownlowSeason's own collision guard is never relied on to surface
 * this as a mid-run failure.
 */
async function checkResidue(seasons: number[]): Promise<boolean> {
  await assertAfldbTest();
  let residueFound = false;
  for (const season of seasons) {
    const prefix = `issue155-${season}-`;
    const [seasonRow] = await sql<{ year: number }[]>`SELECT year FROM seasons WHERE year = ${season}`;
    const [matchCount] = await sql<{ n: number }[]>`
      SELECT count(*)::int AS n FROM matches WHERE match_key LIKE ${`${prefix}%`}
    `;
    const [playerCount] = await sql<{ n: number }[]>`
      SELECT count(*)::int AS n FROM players WHERE slug LIKE ${`${prefix}%`}
    `;
    const hasResidue = !!seasonRow || matchCount.n > 0 || playerCount.n > 0;
    if (hasResidue) {
      residueFound = true;
      console.log(
        `Residue for season ${season}: seasons row=${!!seasonRow}, `
        + `matches=${matchCount.n}, players=${playerCount.n}`,
      );
    }
  }
  return residueFound;
}

async function main(): Promise<void> {
  const mode = process.argv[2];
  if (mode === 'create') await create();
  else if (mode === 'cleanup') await cleanup();
  else if (mode === 'check') {
    const residue = await checkResidue([BROWNLOW_MAIN_SEASON, BROWNLOW_SHORT_SEASON]);
    process.exitCode = residue ? 2 : 0;
  } else {
    console.error('Usage: issue155-acceptance-fixtures.ts create|cleanup|check');
    process.exit(1);
  }
}

main()
  .catch((error) => { console.error(error); process.exitCode = 1; })
  .finally(async () => { await sql.end({ timeout: 5 }); });
'@ | Set-Variable -Name tsHereString

    # Windows PowerShell 5.1's `Set-Content -Encoding utf8` always writes a
    # UTF-8 BOM. esbuild (via tsx) only recognises a shebang when '#!' are
    # the literal first two bytes of the file; a BOM in front of
    # '#!/usr/bin/env tsx' makes it try to parse the shebang as TypeScript
    # source instead, and fails with "Syntax error "!"" before a single
    # line of the module -- including the @/db/client import -- ever runs.
    # Write explicit UTF-8 WITHOUT a BOM instead.
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($scriptPath, $tsHereString, $utf8NoBom)

    # --- 5. Preflight: prove the generated file is not itself broken, and
    # that any check we do costs zero DB interaction, before trusting it. ---

    $firstBytes = [System.IO.File]::ReadAllBytes($scriptPath) | Select-Object -First 3
    $isBom = ($firstBytes.Count -eq 3 -and $firstBytes[0] -eq 0xEF -and $firstBytes[1] -eq 0xBB -and $firstBytes[2] -eq 0xBF)
    if ($isBom) {
        throw "Refusing: generated $scriptPath still begins with a UTF-8 BOM."
    }
    $firstLine = (Get-Content -Path $scriptPath -TotalCount 1)
    if ($firstLine -ne '#!/usr/bin/env tsx') {
        throw "Refusing: generated $scriptPath does not begin with the expected shebang line. Got: '$firstLine'"
    }
    Write-Host "Preflight OK: no BOM, shebang line intact." -ForegroundColor Green

    # Zero-execution syntax/transform check: uses tsx's OWN bundled esbuild
    # JS API (transformSync) to compile the file's TypeScript to JS text and
    # discard the result. This never requires or evaluates the module --
    # @/db/client is never imported, no connection is ever opened -- it only
    # proves the source parses. This is the same esbuild that rejected the
    # BOM'd file originally, so it is authoritative for exactly this class
    # of failure. Always writes to stdout only, never stderr, and the exit
    # code is the sole and only signal, so there is no expected-stderr path
    # for PowerShell to misreport as a NativeCommandError.
    $esbuildMainPath = Join-Path $repoRoot 'node_modules\tsx\node_modules\esbuild\lib\main.js'
    if (-not (Test-Path $esbuildMainPath)) {
        throw "Refusing: bundled esbuild not found at $esbuildMainPath (expected via tsx's own dependency)."
    }
    $checkJsPath = Join-Path $repoRoot 'tools\admin\issue155-acceptance-preflight.cjs'
    @'
'use strict';
const fs = require('fs');
const esbuildMainPath = process.argv[2];
const tsFilePath = process.argv[3];
const esbuild = require(esbuildMainPath);
const source = fs.readFileSync(tsFilePath, 'utf8');
try {
  esbuild.transformSync(source, { loader: 'ts' });
  process.stdout.write('PREFLIGHT_TRANSFORM_OK\n');
  process.exit(0);
} catch (err) {
  process.stdout.write('PREFLIGHT_TRANSFORM_FAILED\n');
  process.stdout.write(String(err && err.message ? err.message : err) + '\n');
  process.exit(1);
}
'@ | Set-Variable -Name checkJsBody
    [System.IO.File]::WriteAllText($checkJsPath, $checkJsBody, $utf8NoBom)

    $previousEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $preflightOutput = & node $checkJsPath $esbuildMainPath $scriptPath
        $preflightExit = $LASTEXITCODE
    }
    finally {
        $ErrorActionPreference = $previousEap
        if (Test-Path $checkJsPath) { Remove-Item -Path $checkJsPath -ErrorAction SilentlyContinue }
    }

    if ($preflightExit -ne 0 -or ($preflightOutput -notmatch 'PREFLIGHT_TRANSFORM_OK')) {
        Write-Host "--- preflight transform output ---" -ForegroundColor Yellow
        $preflightOutput | Write-Host
        throw "Refusing: syntax/transform preflight of $scriptPath failed (exit code $preflightExit). No database action was attempted."
    }
    Write-Host "Preflight OK: TypeScript transform succeeded with zero module evaluation and zero DB interaction." -ForegroundColor Green

    # --- 7. READ-ONLY residue check, BEFORE prompting for a password. Never
    # writes anything -- refuses immediately if a prior CREATE (interrupted,
    # partially failed, or otherwise) already left fixture rows behind, so
    # this run never overlaps seedBrownlowSeason's own collision guard mid-run.
    $previousEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $checkOutput = & npx tsx $scriptPath check
        $checkExit = $LASTEXITCODE
    }
    finally {
        $ErrorActionPreference = $previousEap
    }
    $checkOutput | Write-Host
    if ($checkExit -eq 2) {
        Write-Host ''
        Write-Host 'REFUSED: stale ISSUE-155 acceptance fixture residue exists in afldb_test.' -ForegroundColor Red
        Write-Host 'Run:' -ForegroundColor Red
        Write-Host '  powershell -ExecutionPolicy Bypass -File .\tools\admin\issue155-acceptance-cleanup.ps1' -ForegroundColor Red
        throw 'Refusing: stale fixture residue found by the read-only check. No password was prompted for and nothing was written.'
    }
    if ($checkExit -ne 0) {
        throw "Refusing: residue check exited with unexpected code $checkExit. No password was prompted for and nothing was written."
    }
    Write-Host "Residue check OK: afldb_test has no ISSUE-155 fixture rows for seasons 2089/2085." -ForegroundColor Green

    # --- 8. Prompt once for the disposable password. Never echoed, never printed. ---

    $securePwd = Read-Host -Prompt 'Disposable password for all 3 fixture accounts (min 12 chars)' -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePwd)
    try {
        $env:AFLDB_FIXTURE_PASSWORD = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    }
    finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }

    # --- 9. Run it for real ---
    #
    # Scoped to 'Continue': the real create() logs its own refusals and
    # errors via console.error (by design, so they are visible), and under
    # 'Stop' any such stderr line from a native process is itself wrapped
    # into a terminating NativeCommandError by Windows PowerShell 5.1 --
    # exactly the failure mode this whole preflight redesign exists to
    # avoid. $LASTEXITCODE remains the sole authority on success/failure.
    $previousEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        npx tsx $scriptPath create
    }
    finally {
        $ErrorActionPreference = $previousEap
    }
    if ($LASTEXITCODE -ne 0) {
        throw "issue155-acceptance-fixtures.ts create exited with code $LASTEXITCODE"
    }
}
finally {
    if (Test-Path $scriptPath) {
        Remove-Item -Path $scriptPath -ErrorAction SilentlyContinue
    }
    $env:AFLDB_FIXTURE_PASSWORD = $originalFixturePassword
    $env:NODE_OPTIONS = $originalNodeOptions
    $env:DATABASE_URL = $originalDatabaseUrl
    $env:AFLDB_TEST_DATABASE_URL = $originalTestDatabaseUrl
}
